Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -70,6 +70,9 @@ jobs:
     - uses: webfactory/ssh-agent@v0.9.0
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+    - name: Test HTTPS connectivity to CodebaseHQ
+      run: |
+        curl -v https://codebasehq.com || echo "curl failed" 
     - name: Mercurial Clone
       run: |
         hg clone --updaterev "${{ inputs.updaterev }}" https://${{ secrets.CODEBASE_USERNAME }}:${{ secrets.CODEBASE_PASSWORD }}@digi-labs.codebasehq.com/cerulean/sonarview.hg .
